// <auto-generated />
using System;
using BandAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BandAPI.Migrations
{
    [DbContext(typeof(BandAlbumContext))]
    [Migration("20200213072706_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(400)")
                        .HasMaxLength(400);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fad373fc-f59e-4666-a6d0-ce84abad4ce2"),
                            BandId = new Guid("cf7e2071-cadc-4cfa-a197-d37a708be991"),
                            Description = "One of the best heavy metal albums ever",
                            Title = "Master of Puppets"
                        },
                        new
                        {
                            Id = new Guid("3e6e88e7-18f2-4532-8320-b81a09aee05f"),
                            BandId = new Guid("cf7e2071-cadc-4cfa-a197-d37a708be991"),
                            Description = "Legen Soul Music",
                            Title = "King in the Heaven"
                        },
                        new
                        {
                            Id = new Guid("008f39cc-ae29-44f2-8929-9b13fda96079"),
                            BandId = new Guid("12a1c828-aaa3-4940-98ab-3625347fac3a"),
                            Description = "Classic Piano Performance",
                            Title = "Green Piano"
                        },
                        new
                        {
                            Id = new Guid("bfcb9600-907f-4606-ae2e-ed11db784eb9"),
                            BandId = new Guid("6ff5c7b0-5465-4e21-a346-4564b34dda62"),
                            Description = "Ophera Music",
                            Title = "Lion King"
                        },
                        new
                        {
                            Id = new Guid("9b4d14b1-40d4-4886-8b6b-58d8f3cf173f"),
                            BandId = new Guid("ed69f31c-7475-45c0-a062-55f7c7245af5"),
                            Description = "Testing Description",
                            Title = "Albumn Name"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Band", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Founded")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainGenre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Bands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12a1c828-aaa3-4940-98ab-3625347fac3a"),
                            Founded = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Heavy Metal",
                            Name = "Band 2"
                        },
                        new
                        {
                            Id = new Guid("ed69f31c-7475-45c0-a062-55f7c7245af5"),
                            Founded = new DateTime(1980, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Pop",
                            Name = "Band 3"
                        },
                        new
                        {
                            Id = new Guid("50b56f93-20b9-4b49-96ce-5556d2ccee6d"),
                            Founded = new DateTime(1980, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Style 3",
                            Name = "Band 4"
                        },
                        new
                        {
                            Id = new Guid("6ff5c7b0-5465-4e21-a346-4564b34dda62"),
                            Founded = new DateTime(1980, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Style 4",
                            Name = "Band 5"
                        },
                        new
                        {
                            Id = new Guid("cf7e2071-cadc-4cfa-a197-d37a708be991"),
                            Founded = new DateTime(1980, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MainGenre = "Style 5",
                            Name = "Band 6"
                        });
                });

            modelBuilder.Entity("BandAPI.Entities.Album", b =>
                {
                    b.HasOne("BandAPI.Entities.Band", "Band")
                        .WithMany("Albums")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
